# -*- coding: utf-8 -*-
"""03-clases

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_6ez2E8HWEqCxiYJfhE-NTM39CLJL8_f
"""

class Mascota:
  #propiedades

  #Constructor
  def __init__(self, nombre: str, raza: str, edad: float):
    self.nombre = nombre
    self.raza = raza
    self.edad = edad

  #comportaminetos (metodos )
  def ladrar(self):
    print(f"{self.nombre} está ladrando")

apolo = Mascota(nombre = "Apolo", raza = "Terrier", edad = 3)

print(apolo.nombre)
print(apolo.raza)
print(apolo.edad)

apolo.ladrar()

# modelo : turismo ( 2% ) o pick-up ( 6% )
# dias
# precio por dia: 100


# calcular precio