# -*- coding: utf-8 -*-
"""05-numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DAW7Vrrf0MdAXUaCCtvjwREriyRyvvi7
"""

numeros = [1,2,3,4,5,6]

numeros2  = [[1,2,3], [1,2,3], [1,2,3, 4]]

numeros2

# ! pip install numpy

#importamos numpy
import numpy as np

np_array = np.array(numeros, dtype=float)

np_array2 = np.array([[1,2,3], [1,2,3], [1,2,3]])

print(np_array.shape)
print(np_array2.shape)

# [[1,2,3], [1,2,3], [1,2,3]]
# [1,2,3,4,5,6] -> [[1],[2],[3],...]



reshape_array = np_array.reshape(-1,1)

reshape_array

np_array