# -*- coding: utf-8 -*-
"""Seaborn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PAEHAvxFF0E-y5LEKmRcWfJVKKeBhiQ
"""

import pandas as pd # me permite trabajar con dataframes
import seaborn as sb # me permite graficar info

df = pd.read_csv('Fullmetadata.csv')
df.head()

goles_por_equipo = df.groupby('team_name')['goals'].sum().reset_index()

goles_por_equipo

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sb.barplot(data=goles_por_equipo.head(),
           x='team_name',
           y='goals',
           hue='goals', #colorear cada barra de un color distinto
           )

df_barcelona = df[(df['team_name'] == 'Real Madrid') & (df['year'] < 2020 ) ]
goles_barcelona = df_barcelona.groupby('year')['goals'].sum().reset_index()

plt.figure(figsize=(10, 6))
sb.lineplot(data=goles_barcelona,
            x='year',
            y='goals',
            marker='o',
            )

#la cantidad de jugadores por possicion
plt.figure(figsize=(10, 6))
sb.countplot(data=df, x='position')