# -*- coding: utf-8 -*-
"""Regresión Logistica

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7rGulUNaQ3Rtn7841u_Xwz5JGp2J_Rj
"""

import pandas as pd

df = pd.read_csv('./Titanic-Dataset.csv')

df.head()

df.Ticket.value_counts()

df.drop(['Ticket','Cabin','PassengerId','Name'], axis = 1, inplace = True)

df.head()

df.describe()

import seaborn as sb

sb.countplot( data=df, x='Survived' )

sb.countplot( data=df, x='Survived' , hue='Embarked')

sb.countplot( data=df, x='Survived' , hue='Pclass')

dummies_sex = pd.get_dummies(df['Sex'], dtype=int, drop_first=True)

dummies_sex.head()

df = df.join(dummies_sex)

embarked_dummies = pd.get_dummies(df['Embarked'], dtype=int, drop_first=True)
df = df.join(embarked_dummies)

df.drop(['Sex','Embarked'], axis = 1, inplace = True)
df.head()

df.isna().sum()

sb.countplot(data=df.loc[df.Age.isna()], x='Survived', hue='male')

df.fillna(df.Age.mean(), inplace=True)

sb.heatmap(df.corr(), annot=True, cmap='YlGnBu')

# Separar la etiqueta de las caracteristicas
X = df.drop(['Survived','Q','S'], axis = 1)
y = df['Survived']

df.shape

#Separar en conjuntos de entrenamiento y pruebas

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

from sklearn.linear_model import LogisticRegression

# Instancia del modelo
model = LogisticRegression(max_iter=1000)

# Entrenamiento
model.fit(X_train, y_train)

#predicciones

predicciones = model.predict(X_test)

predicciones

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, predicciones)
asc = accuracy_score(y_test, predicciones)

print(cm)
print(asc)
print(model.score(X_test, y_test))

pd.DataFrame(cm, columns=['Pred No', 'Pred Si'], index=['Real No', 'Real Si'])

X.head(1)

X.loc[X.Pclass == 2,:].Fare.mean()

model.predict([ [ 2 , 1, 0, 0, 30, 1 ] ])

df_test = pd.read_csv('./Titanic-Dataset.csv')

# df_test.loc[df_test.Embarked.isna()]
pd.get_dummies(df_test.loc[df_test.Embarked.isna()].Embarked)